### ISSUE TITLE
As a user, I want to see a group’s profile page

### ISSUE THREAD

**Issue by trezy** [RollForGuild/TheGM#27]
## Acceptance Criteria

- [x] A group's profile can be retrieved from `GET /groups/:group_id`
- [x] The profile should return:
  - [x] The group's profile details
  - [x] The user's request status (whether or not the user has requested to join the group)
  - [x] The user's member status (whether or not the user is already a member)

**Comment by QMalcolm** [comment]
Resolved by #54
