### ISSUE TITLE
Groups search is returning incorrect structure

### ISSUE THREAD

**Issue by trezy** [RollForGuild/TheGM#43]
The groups search should be returning something like this:

```
{
  meta: {},
  data: [
    {
      attributes: {},
      id: '...',
      type: '...',
    }
  ]
}
```

Instead, it's returning this:

```
{
  meta: {},
  data: [
    { ... }
  ]
}
```

It looks like the group entities being returned are the contents of the `attributes` prop, rather than an object with `attributes`, `id`, and `type` prop. This is blocking RollForGuild/rollforguild.com#12.

**Comment by QMalcolm** [comment]
Resolved by #47
