### ISSUE TITLE
Group creation is broken

### ISSUE THREAD

**Issue by trezy** [RollForGuild/TheGM#51]
The error I receive is `Invalid argument; Expected: :dns|:url|:oid|:x500|:nil OR String, String`. I assume we're missing a new required property, but I don't know what that is and the request in Postman hasn't been updated. Authenticating and then sending the `Groups/Create Group` request in Postman will reproduce the error.

![](https://trezy.sh/2emdAW.png)

This is blocking RollForGuild/rollforguild.com#12.

**Comment by QMalcolm** [comment]
This was due to the Postman example not being updated.
