### ISSUE TITLE
As a user, I want to see a list of groups of which I am a member

### ISSUE THREAD

**Issue by trezy** [RollForGuild/TheGM#56]
## Acceptance Criteria

- [ ] I can retrieve a list of groups of which I am a member **(Route still needs to be determined)**

## Blocking

- RollForGuild/rollforguild.com#51

**Comment by QMalcolm** [comment]
@trezy Would you also like this information to be loaded into the user profile? It would be similar to how group members are loaded:

1. the attributes would have a **groups** key with the value being the count of groups 
2. the user viewing their own profile would also have the **relationships** and **included** data parts for the individual groups

**Comment by QMalcolm** [comment]
Already solved by @xlexi
